import type { Game } from "../types/game";
import { normalizeTitle } from "../utils/normalizeTitle";

export const devGames: Game[] = [
  createGame({
    id: 1,
    title: "Hades",
    releaseYear: 2020,
    isPlayed: true,
    isCompleted: true,
    isFavorite: true,
    isInstalled: true,
    steamAppId: 1145360,
    genreNames: ["Action", "Roguelike"],
    platformNames: ["PC", "Steam Deck"],
    multiplayerType: "singleplayer",
    steamDeckCompatible: "yes",
    estimatedLength: "short",
  }),
  createGame({
    id: 2,
    title: "Baldur's Gate 3",
    releaseYear: 2023,
    isPlayed: true,
    isCurrentlyPlaying: true,
    isFavorite: true,
    isInstalled: true,
    steamAppId: 1086940,
    genreNames: ["RPG", "Strategy"],
    platformNames: ["PC"],
    multiplayerType: "both",
    steamDeckCompatible: "yes",
    estimatedLength: "long",
  }),
  createGame({
    id: 3,
    title: "Stardew Valley",
    releaseYear: 2016,
    isPlayed: true,
    steamAppId: 413150,
    genreNames: ["Cozy", "Simulation"],
    platformNames: ["Nintendo Switch", "PC"],
    multiplayerType: "both",
    steamDeckCompatible: "yes",
    estimatedLength: "medium",
  }),
  createGame({
    id: 4,
    title: "Disco Elysium",
    releaseYear: 2019,
    steamAppId: 632470,
    genreNames: ["Detective", "RPG"],
    platformNames: ["PC"],
    multiplayerType: "singleplayer",
    steamDeckCompatible: "yes",
    estimatedLength: "long",
  }),
  createGame({
    id: 5,
    title: "Old Competitive Shooter",
    releaseYear: 2014,
    isPlayed: true,
    isAbandoned: true,
    isWishlisted: false,
    neverShowInRandom: true,
    source: "import",
    genreNames: ["Competitive", "FPS"],
    platformNames: ["PC"],
    multiplayerType: "multiplayer",
    estimatedLength: "short",
  }),
];

function createGame(overrides: Partial<Game> & Pick<Game, "id" | "title" | "releaseYear">): Game {
  const now = new Date().toISOString();

  return {
    coverPath: null,
    usePlaceholderCover: true,
    personalRating: null,
    notes: null,
    estimatedLength: "unknown",
    turkishLanguageSupport: "unknown",
    turkishPatchAvailable: false,
    isPlayed: false,
    isCompleted: false,
    isFavorite: false,
    isCurrentlyPlaying: false,
    isAbandoned: false,
    isInstalled: false,
    isWishlisted: false,
    neverShowInRandom: false,
    multiplayerType: "unknown",
    steamDeckCompatible: "unknown",
    source: "manual",
    steamAppId: null,
    createdAt: now,
    updatedAt: now,
    ...overrides,
    id: overrides.id,
    title: overrides.title,
    normalizedTitle: overrides.normalizedTitle ?? normalizeTitle(overrides.title),
    releaseYear: overrides.releaseYear,
  };
}
